version: 0.2

env:
  secrets-manager:
    API_KEY: "arn:aws:secretsmanager:us-east-2:339713008336:secret:prof/EBEREGIT/app-2aG1t8"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing backend dependencies
      - cd backend
      - npm install
      - cd ../frontend
      - echo Installing frontend dependencies
      - npm install
  pre_build:
    commands:
      - echo Running pre-build commands
      - npm run build
      - cd ..
  build:
    commands:
      - echo Building the backend
      - cd backend
      - npm run build
  post_build:
    commands:
      - echo Post-build started
artifacts:
  files:
    - '**/*'
  base-directory: 'backend'
  discard-paths: yes
cache:
  paths:
    - 'node_modules/**/*'
    - 'frontend/node_modules/**/*'
    - 'backend/node_modules/**/*'