#buildsepc file for AWS CodeBuild
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g pnpm@8.6.3
      - pnpm install

  pre_build:
    commands:
      - echo Running lint...
      - pnpm run lint

  build:
    commands:
      - echo Building the Next.js app...
      - pnpm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: .next

cache:
  paths:
    - 'node_modules/**/*'
