version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
   
    commands:
        - echo Installing dependencies...
        - cd frontend
        - npm install
        - cd ../backend
        - npm install
        - cd ..
       
  build:
    commands:
        - echo Running build script...
        - npm run build
     
artifacts:
  # include all files required to run the application
  files:
    - backend/package.json
    - backend/index.js
    - frontend/public/**/*
    - frontend/src/**/*
    - frontend/package.json
    - appspec.yml
    - frontend/scripts/**/*
