version: 0.2

env:
  secrets-manager:
    API_KEY: "arn:aws:secretsmanager:us-east-2:339713008336:secret:prof/EBEREGIT/app-2aG1t8"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
        - echo Installing dependencies...
        - cd frontend
        - npm install
        - cd ../backend
        - npm install
        - cd ..
       
  build:
    commands:
        - echo Running build script...
        - cd frontend
        - npm run build
     
artifacts:
  files:
    - backend/**/*
    - frontend/dist/**/*
    - frontend/public/**/*
    - frontend/src/**/*
    - frontend/package.json
    - appspec.yml
    - scripts/**/*
