version: 0.2

env:
  secrets-manager:
    API_KEY: "arn:aws:secretsmanager:us-east-2:339713008336:secret:prof/EBEREGIT/app-2aG1t8"
    DOCKER_USER: "arn:aws:secretsmanager:us-east-2:339713008336:secret:qa/AIBot/Docker-zxU2EX:DOCKER_USER"
    DOCKER_PASSWORD: "arn:aws:secretsmanager:us-east-2:339713008336:secret:qa/AIBot/Docker-zxU2EX:DOCKER_PASSWORD"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y openjdk-17-jdk
      - update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
      - update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - echo Installing npm dependencies...
      - cd frontend
      - npm install
      - cd ../backend
      - npm install
      - cd ..
  pre_build:
    commands:
      - echo Starting backend server...
      - cd backend
      - nohup node index.js &
      - cd ..
      - echo Starting frontend server...
      - cd frontend
      - nohup npm run build
      - nohup npm start -- --port 4173 &
      - cd ..
      - echo Waiting for the application to start...
      - sleep 120
      - echo Checking if the application is running...
      - curl http://localhost:4173  # Add a simple check to see if the application is accessible
  build:
    commands:
      - echo Pulling OWASP ZAP Docker image...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - docker pull zaproxy/zap-weekly
      - echo Running OWASP ZAP scan...
      - docker run -v $(pwd):/zap/wrk:rw --network="host" zaproxy/zap-weekly zap-full-scan.py -t http://localhost:4173 -r zap-report.html
  post_build:
    commands:
      - echo Copying ZAP report...
      - cp zap-report.html ./zap-report.html
artifacts:
  files:
    - backend/**/*
    - frontend/dist/**/*
    - frontend/public/**/*
    - frontend/src/**/*
    - frontend/package.json
    - appspec.yml
    - scripts/**/*
    - /home/zap/zap-report.html
