#buildspec file for AWS CodeBuild
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR Public..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

  build:
    commands:
      - echo "Building Docker image tagged as IMAGE_REPO_NAME:IMAGE_TAG..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo "Tagging the image for AWS ECR Public repository..."
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/$ALIAS/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker image to AWS ECR Public..."
      - docker push public.ecr.aws/$ALIAS/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"DevSecOps-App-01","imageUri":"public.ecr.aws/%s/%s:%s"}]' $ALIAS $IMAGE_REPO_NAME $IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - scripts/*