version: 0.2

env:
  secrets-manager:
    API_KEY: "arn:aws:secretsmanager:us-east-2:339713008336:secret:prof/EBEREGIT/app-2aG1t8"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing backend dependencies
      - cd backend
      - npm install
      - cd ../frontend
      - echo Installing frontend dependencies
      - npm install
      - cd ..
  pre_build:
    commands:
      - echo Building frontend
      - cd frontend
      - npm run build
      - cd ..
  build:
    commands:
      - echo Packaging application
      - zip -r app.zip .
  post_build:
    commands:
      - echo Deploying to Elastic Beanstalk
      - eb init -p node.js -r us-east-2
      - eb use Call-of-Duty-AI-Bot-01-514-Beans-env  
      - eb deploy
artifacts:
  files:
    - app.zip
  discard-paths: yes
