version: 0.2

env:
  secrets-manager:
    API_KEY: "arn:aws:secretsmanager:us-east-2:339713008336:secret:prof/EBEREGIT/app-2aG1t8"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing backend dependencies
      - cd backend
      - npm install
      - cd ../frontend
      - echo Installing frontend dependencies
      - npm install
      - cd ..
      - echo Installing EB CLI
      - pip install --upgrade pip
      - pip install awsebcli --upgrade --user
      - export PATH=$PATH:$HOME/.local/bin
  pre_build:
    commands:
      - echo Building frontend
      - cd frontend
      - npm run build
      - cd ..
  build:
    commands:
      - echo Packaging application
      - zip -r app.zip .
  files:
    - app.zip
  discard-paths: yes
