#buildsepc file for AWS CodeBuild
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo "Building Docker image tagged as my-image:$IMAGE_TAG..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo "Tagging the image for AWS ECR repository..."
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing the Docker image to AWS ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"cicd-pipeline","imageUri":"%s.dkr.ecr.%s.amazonaws.com/my-image:%s"}]' $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION $IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json