version: 0.2

env:
  secrets-manager:
    API_KEY: "arn:aws:secretsmanager:us-east-2:339713008336:secret:prof/EBEREGIT/app-2aG1t8"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing backend dependencies
      - cd backend
      - npm install
      - cd ../frontend
      - echo Installing frontend dependencies
      - npm install
  pre_build:
    commands:
      - echo Building frontend
      - npm run build
      - cd ..
  build:
    commands:
      - echo Running backend
      - cd backend
      - echo no need to 'node index.js' right now
artifacts:
  files:
    - '**/*'
  base-directory: 'backend'
  discard-paths: yes
