version: 0.2

env:
  secrets-manager:
    API_KEY: "arn:aws:secretsmanager:us-east-2:339713008336:secret:prof/EBEREGIT/app-2aG1t8"

phases:
  install:
    runtime-versions:
     java: corretto17
      nodejs: 20
      commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y openjdk-17-jdk
      - update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
      - update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - echo Installing dependencies...
      - cd frontend
      - npm install
      - cd ../backend
      - npm install
      - cd ..
      - echo Installing OWASP ZAP...
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2_15_0_unix.sh
      - chmod +x ZAP_2_15_0_unix.sh
      - ./ZAP_2_15_0_unix.sh -q -dir /home/zap
      - echo Verifying OWASP ZAP installation...
      - pwd
      - ls -la /home
      - ls -la /home/zap
      - ls -R /home/zap/ZAP_2_15_0
      - find /home/zap -name zap.sh
  pre_build:
    commands:
      - echo Starting OWASP ZAP...
      - /home/zap/ZAP_2_15_0/zap.sh -daemon -config api.disablekey=true
  build:
    commands:
      - echo Running build script...
      - cd frontend
      - npm run build
      - cd ..
      - echo Running OWASP ZAP scan...
      - /home/zap/ZAP_2_15_0/zap-cli quick-scan --self-contained --start-options '-config api.disablekey=true' http://your-application-url
  post_build:
    commands:
      - echo Post build actions...
      - /home/zap/ZAP_2_15_0/zap-cli report -o zap-report.html -f html
artifacts:
  files:
    - backend/**/*
    - frontend/dist/**/*
    - frontend/public/**/*
    - frontend/src/**/*
    - frontend/package.json
    - appspec.yml
    - scripts/**/*
    - zap-report.html
