version: '3.8'

services:
  backend:
    build:
      context: ./backend
      
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - API_KEY=${API_KEY}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
